server.port=8080
server.servlet.context-path=/api

# H2 In-Memory Database for local testing
spring.datasource.url=jdbc:h2:mem:eneba_test_db
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# JPA/Hibernate
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.h2.console.enabled=true

# Logging
logging.level.com.eneba=DEBUG
logging.level.org.springframework.web=INFO
